SRCS = ./srcs/main.c\
./srcs/types/string/string_init.c\
./srcs/types/string/string_len.c\
./srcs/types/string/string_dup.c\
./srcs/types/dict/dict_append.c\
./srcs/types/dict/dict_search.c\
./srcs/types/dict/dict_init.c\
./srcs/types/entry/entry_init.c\
./srcs/parsing/syntax/syntaxer.c\
./srcs/parsing/syntax/syntax_operator/syntax_pipe.c\
./srcs/parsing/syntax/syntax_operator/syntax_and.c\
./srcs/parsing/syntax/syntax_operator/syntax_dquote.c\
./srcs/parsing/syntax/syntax_operator/syntax_or.c\
./srcs/parsing/syntax/syntax_operator/syntax_squote.c\
./srcs/parsing/syntax/syntax_operator/syntax_open.c\
./srcs/parsing/syntax/syntax_operator/syntax_close.c\
./srcs/parsing/syntax/syntax_operator/syntax_heredoc.c\
./srcs/parsing/syntax/syntax_operator/syntax_in.c\
./srcs/parsing/syntax/syntax_operator/syntax_out.c\
./srcs/parsing/syntax/syntax_operator/syntax_append.c\
./srcs/parsing/syntax/syntax_operator.c\
./srcs/parsing/utils/skipto.c\
./srcs/alloc/smalloc.c\
./srcs/env/env_init.c\
./srcs/mem/mem_move.c\
